// Generated by CoffeeScript 1.10.0
this.Dot = (function() {
  function Dot(x1, y1) {
    this.x = x1;
    this.y = y1;
  }

  Dot.prototype.draw = function(r, g, b) {
    stroke(r, g, b, 10);
    fill(r, g, b, 10);
    return ellipse(this.x, this.y, 10, 10);
  };

  Dot.prototype.highlight = function(r, g, b) {
    stroke(r, g, b, 50);
    fill(r, g, b, 50);
    return ellipse(this.x, this.y, 10, 10);
  };

  return Dot;

})();

this.Grid = (function() {
  function Grid() {
    var i, j, k, l, ref, ref1;
    this.dots = {};
    for (i = k = 0, ref = width; k < ref; i = k += 20) {
      for (j = l = 0, ref1 = height; l < ref1; j = l += 20) {
        this.dots[[i, j]] = new Dot(i + 10, j + 10);
      }
    }
  }

  Grid.prototype.near = function(x, y) {
    var i, j;
    i = 20 * floor(x / 20);
    j = 20 * floor(y / 20);
    return this.dots[[i, j]];
  };

  Grid.prototype.draw = function() {
    var _, d, ref, results;
    ref = this.dots;
    results = [];
    for (_ in ref) {
      d = ref[_];
      results.push(d.draw(200, 200, 200));
    }
    return results;
  };

  return Grid;

})();
