// Generated by CoffeeScript 1.10.0
var Dot, Grid, Walker, draw, mouseClicked, polygonal, ref, ref1, sample, setup;

ref = require('./app/grid'), Grid = ref.Grid, Dot = ref.Dot;

Walker = require('./app/walker').Walker;

ref1 = require('./app/utility'), sample = ref1.sample, polygonal = ref1.polygonal;

setup = function() {
  createCanvas(windowWidth, windowHeight);
  frameRate(50);
  stroke(200, 200, 125, 20);
  fill(200, 200, 125, 20);
  this.walkers = [];
  this.g = new Grid();
  this.g.draw();
};

draw = function() {
  var i, len, ref2, w;
  background(255);
  this.g.draw();
  ref2 = this.walkers;
  for (i = 0, len = ref2.length; i < len; i++) {
    w = ref2[i];
    w.update();
    w.draw();
  }
  if (key === 'p') {
    return noLoop();
  }
};

mouseClicked = function() {
  return this.walkers.push(new Walker(createVector(mouseX, mouseY), this.g));
};
