// Generated by CoffeeScript 1.10.0
this.Walker = (function() {
  function Walker(position, grid) {
    this.position = position;
    this.grid = grid;
    this.r = random(255);
    this.g = random(255);
    this.b = random(255);
    this.trail = [];
    this.direction = sample([0, PI / 4, PI / 2, 3 * PI / 4, PI, 5 * PI / 4, 6 * PI / 4, 7 * PI / 4]);
    ellipse(this.position.x, this.position.y, 10, 10);
  }

  Walker.prototype.update = function() {
    var dot, newDirection, newVec;
    newDirection = sample([0, 0, 0, PI / 2, -PI / 2, PI / 4, -PI / 4]);
    newDirection = newDirection + this.direction;
    this.lastPosition = this.position;
    newVec = p5.Vector.fromAngle(newDirection);
    this.position = p5.Vector.add(this.position, newVec.setMag(20));
    this.direction = newDirection;
    dot = this.grid.near(this.position.x, this.position.y);
    if (dot !== void 0) {
      return this.trail.push(dot);
    }
  };

  Walker.prototype.draw = function() {
    var d, i, len, ref;
    stroke(this.r, this.g, this.b, 100);
    ref = this.trail;
    for (i = 0, len = ref.length; i < len; i++) {
      d = ref[i];
      d.highlight(this.r, this.g, this.b);
    }
    return polygonal(this.trail);
  };

  return Walker;

})();
