// Generated by CoffeeScript 1.10.0
var Vector, Walker, draw, iteration, maxWalkers, r, setup, tree, walkers;

Vector = p5.Vector;

Walker = require('./app/walker').Walker;

tree = [];

r = 2;

maxWalkers = 2000;

iteration = 10;

walkers = [];

setup = function() {
  var i, j, ref, w, walker;
  createCanvas(windowWidth, windowHeight);
  background(51);
  w = new Walker(r);
  w.pos = createVector(width / 2, height / 2);
  tree[0] = w;
  for (i = j = 1, ref = maxWalkers; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
    walker = new Walker(r);
    walkers.push(walker);
  }
  return fill(100);
};

draw = function() {
  var j, k, l, len, len1, m, n, p, ref, results, walker;
  background(51);
  for (j = 0, len = tree.length; j < len; j++) {
    p = tree[j];
    noStroke();
    p.draw();
  }
  for (k = 0, len1 = walkers.length; k < len1; k++) {
    walker = walkers[k];
    walker.draw();
  }
  for (n = l = 1, ref = iteration; 1 <= ref ? l <= ref : l >= ref; n = 1 <= ref ? ++l : --l) {
    for (m = walkers.length - 1; m >= 0; m += -1) {
      walker = walkers[m];
      walker.check(tree);
      if (!walker.stuck) {
        walker.walk();
      } else {
        tree.push(walker);
        walkers.splice(walkers.indexOf(walker), 1);
      }
    }
  }
  results = [];
  while (walkers.length < maxWalkers) {
    results.push(walkers.push(new Walker(r)));
  }
  return results;
};
