// Generated by CoffeeScript 1.10.0
var randomFromDirection;

this.Walker = (function() {
  function Walker(r) {
    this.r = r;
    this.pos = createVector(random(width), random(height));
    this.stuck = false;
  }

  Walker.prototype.walk = function() {
    var vel;
    vel = Vector.random2D();
    this.pos = this.pos.add(vel.mult(3));
    this.pos.x = constrain(this.pos.x, 0, width);
    this.pos.y = constrain(this.pos.y, 0, height);
    return 0;
  };

  Walker.prototype.check = function(others) {
    var distance, i, len, p;
    for (i = 0, len = others.length; i < len; i++) {
      p = others[i];
      distance = this.dist(this.pos, p.pos);
      if (distance < 3.5 * this.r * p.r) {
        this.stuck = true;
        return true;
      }
    }
    this.stuck = false;
    return false;
  };

  Walker.prototype.draw = function() {
    ellipse(this.pos.x, this.pos.y, 2 * this.r, 2 * this.r);
    return 0;
  };

  Walker.prototype.dist = function(v, w) {
    return Math.pow(v.x - w.x, 2) + Math.pow(v.y - w.y, 2);
  };

  return Walker;

})();

randomFromDirection = function(margin) {
  var coinX, coinY, x, y;
  coinX = random();
  coinY = random();
  if (coinX < 0.5) {
    x = random(margin);
  } else {
    x = random(width - margin, width);
  }
  if (coinY < 0.5) {
    y = random(margin);
  } else {
    y = random(height - margin, height);
  }
  return createVector(x, y);
};
