// Generated by CoffeeScript 1.10.0
var customLine, customLine2, strokePath;

strokePath = function(path) {
  var index, j, p1, p2, ref, results, w, x1, x2, y1, y2;
  if (path.length > 1) {
    results = [];
    for (index = j = 0, ref = path.length - 1; 0 <= ref ? j < ref : j > ref; index = 0 <= ref ? ++j : --j) {
      p1 = path[index];
      p2 = path[index + 1];
      x1 = p1[0], y1 = p1[1];
      x2 = p2[0], y2 = p2[1];
      randomSeed(x1 * y1 * x2 * y2);
      stroke(250);
      w = 5 * random(1, 2);
      strokeWeight(w);
      results.push(line(x1, y1, x2, y2));
    }
    return results;
  }
};

customLine = function(x1, y1, x2, y2) {
  var i, j, p1, p2, ps;
  ps = [[x1, y1]];
  for (i = j = 0; j < 1; i = j += 0.01) {
    p1 = lerp(x1, x2, i);
    p2 = lerp(y1, y2, i);
    ps.push([p1, p2]);
  }
  ps.push([x2, y2]);
  return strokePath(ps);
};

customLine2 = function(x1, y1, x2, y2) {
  var h, ps, v;
  ps = [[x1, y1]];
  v = createVector(x2 - x1, y2 - y1);
  h = v.heading() + PI;
  strokeWeight(h);
  return line(x1, y1, x2, y2);
};

this.Path = (function() {
  function Path() {
    this.path = [];
  }

  Path.prototype.draw = function() {
    var index, j, p1, p2, ref, results, x1, x2, y1, y2;
    if (this.path.length > 1) {
      results = [];
      for (index = j = 0, ref = this.path.length - 1; 0 <= ref ? j < ref : j > ref; index = 0 <= ref ? ++j : --j) {
        p1 = this.path[index];
        p2 = this.path[index + 1];
        x1 = p1[0], y1 = p1[1];
        x2 = p2[0], y2 = p2[1];
        stroke(250);
        results.push(customLine2(x1, y1, x2, y2));
      }
      return results;
    }
  };

  return Path;

})();
