// Generated by CoffeeScript 1.10.0
this.Grid = (function() {
  function Grid(row, column) {
    this.row = row;
    this.column = column;
    this.scl = floor(height / this.column);
    console.log(this.scl);
  }

  Grid.prototype.draw = function() {
    var i, j, k, ref, results;
    results = [];
    for (i = k = 1, ref = this.row; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
      results.push((function() {
        var l, ref1, results1;
        results1 = [];
        for (j = l = 1, ref1 = this.column; 1 <= ref1 ? l <= ref1 : l >= ref1; j = 1 <= ref1 ? ++l : --l) {
          results1.push(ellipse(i * this.scl, j * this.scl, 10, 10));
        }
        return results1;
      }).call(this));
    }
    return results;
  };

  return Grid;

})();
