// Generated by CoffeeScript 1.10.0
var DNA;

DNA = (function() {
  function DNA(fitness, size) {
    var i, j, ref;
    this.fitness = fitness;
    this.size = size;
    this.mutationRate = 0.01;
    this.genes = [];
    for (i = j = 0, ref = this.size; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      this.genes[i] = random();
    }
  }

  DNA.prototype.crossover = function(other) {
    var child, i, j, midpoint, ref;
    child = new DNA();
    midpoint = int(random(this.genes.length));
    for (i = j = 0, ref = this.genes.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      if (i < midpoint) {
        child.genes[i] = this.genes[i];
      } else {
        child.genes[i] = other.genes[i];
      }
    }
    return child;
  };

  DNA.prototype.mutate = function() {
    var i, j, ref, results;
    results = [];
    for (i = j = 0, ref = this.genes.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      if (random() < this.mutationRate) {
        results.push(this.genes[i] = random(10));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  DNA.prototype.copy = function() {
    var a;
    a = new DNA(this.fitness, this.size);
    a.genes = this.genes.slice();
    return a;
  };

  return DNA;

})();

module.exports = DNA;
