// Generated by CoffeeScript 1.10.0
var Environment;

Environment = (function() {
  function Environment() {
    this.entities = [];
  }

  Environment.prototype.add = function(list) {
    return this.entities.push.apply(this.entities, list);
  };

  Environment.prototype.push = function(element) {
    return this.entities.push(element);
  };

  Environment.prototype.remove = function(element) {
    return this.entities.splice(this.entities.indexOf(element), 1);
  };

  Environment.prototype.filter = function(func) {
    return this.entities.filter(func);
  };

  return Environment;

})();

module.exports = Environment;
