// Generated by CoffeeScript 1.10.0
this.Particle = (function() {
  function Particle(x, y, vx, vy, type, force) {
    this.x = x;
    this.y = y;
    this.vx = vx;
    this.vy = vy;
    this.type = type;
    this.force = force;
    this.nx = this.ny = 0;
    this.nvx = this.nvy = 0;
  }

  Particle.prototype.interact = function(other) {
    var distance, f, fx, fy;
    distance = Math.pow(this.x - other.x, 2) + Math.pow(this.y - other.y, 2);
    f = (this.force + other.force) / distance;
    f = constrain(f, 0, 1700);
    fx = f * (other.x - this.x);
    fy = f * (other.y - this.y);
    this.vx = this.vx + fx;
    return this.vy = this.vy + fy;
  };

  Particle.prototype.update = function() {
    this.x = this.x + this.vx;
    this.y = this.y + this.vy;
    if (this.x < -3000) {
      this.x = 0;
      this.vx = 0;
      this.vy = this.vy + random(-1, 1);
    } else if (this.x > width + 3000) {
      this.x = width;
      this.vx = 0;
      this.vy = this.vy + random(-1, 1);
    }
    if (this.y < -3000) {
      this.y = 0;
      this.vy = 0;
      this.vx = this.vx + random(-1, 1);
    } else if (this.y > height + 3000) {
      this.y = height;
      this.vy = 0;
      this.vx = this.vx + random(-1, 1);
    }
    this.vx = this.vx * 0.5;
    return this.vy = this.vy * 0.5;
  };

  return Particle;

})();
