// Generated by CoffeeScript 1.10.0
var draw, setup;

setup = function() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  frameRate(10);
  this.scl = 40;
  this.w = 1500;
  this.h = 800;
  this.cols = floor(w / scl);
  this.rows = floor(h / scl);
  return background(51);
};

draw = function() {
  var i, j, ref, ref1, results, x, y;
  background(51);
  stroke(100);
  results = [];
  for (y = i = 0, ref = rows; 0 <= ref ? i <= ref : i >= ref; y = 0 <= ref ? ++i : --i) {
    beginShape(TRIANGLE_STRIP);
    for (x = j = 0, ref1 = cols; 0 <= ref1 ? j <= ref1 : j >= ref1; x = 0 <= ref1 ? ++j : --j) {
      vertex(x * scl, y * scl, 10);
      vertex(x * scl, (y + 1) * scl, 20);
    }
    results.push(endShape());
  }
  return results;
};
